export const DOMAIN = "https://api.sectortechnology.uz"
export const GET_CATALOG = "/user/catalog/all?catalog=true&subcatalog=true&category=true"
export const GET_BRANDS = "/user/brand/all";
export const GET_BRAND_POPULAR = "/user/brand/all?isPopular=true";
export const GET_BRAND_SINGLE = "/user/brand"
export const GET_BANNER = "/user/banner/all"
export const GET_POPULAR = "/user/popular/all"
export const GET_PRODUCTS = "/user/product/all"
export const GET_PROMOTION = "/user/promotion/all";
export const GET_PRODUCT_CATEGORY = "/user/product/by-slug"
export const GET_PRODUCT_SINGLE = "/user/product/by-slug" 
export const GET_PROMOTION_SINGLE = "/user/promotion";
export const GET_REGION = "/user/region/all"
export const GET_ME = "/user/auth/me"
export const GET_PRODUCT_FILTER = "/user/filter";
export const CREATE_AGENT = "/user/kontragent/create"
export const GET_AGENT = "/user/kontragent/all"